registryCredsReplicaCount: 1
registryCredsNodeSelector:
  node-role.kubernetes.io/node: "true"

registryCredsImageVersion: 1.8
registryCredsAppDefaultCredsJson: ""

registryCredsResources:
  limits:
    memory: 64Mi
  requests:
    memory: 32Mi